services:
  - type: static
    name: portfolio-website
    env: static
    buildCommand: cd portfolio-website && npm install && npm run build
    publish: portfolio-website/out
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
